name: Deploy to Development Environment

on:
  push:
    branches: [develop]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: nasa-media-explorer-dev
  REPOSITORY_NAME: nasa-media-explorer
  REGION: europe-west2
  REGISTRY: europe-west2-docker.pkg.dev
  SERVICE_ACCOUNT: nasa-media-explorer@nasa-media-explorer.iam.gserviceaccount.com

jobs:
  # Lint and Test Job
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests with coverage
        run: npm run test:coverage -- --run

      - name: Build development application
        run: npm run build:dev

  # Build and Deploy to Development
  deploy-dev:
    name: Build & Deploy to Dev
    needs: [test]
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build development Docker image
        run: |
          # Use development Dockerfile
          docker build -f Dockerfile.dev -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:${{ github.sha }} .
          docker tag ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:${{ github.sha }} \
                     ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:dev-latest

      - name: Push development Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:dev-latest

      - name: Deploy to Cloud Run Development
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/frontend:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 5 \
            --port 8000 \
            --timeout 300 \
            --service-account=${{ env.SERVICE_ACCOUNT }}

      - name: Test development deployment
        run: |
          # Wait for deployment to be ready
          sleep 30
          
          # Get service URL
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region=${{ env.REGION }} \
            --format='value(status.url)')
          
          echo "Development service deployed to: $SERVICE_URL"
          
          # Test main application
          if curl -f "$SERVICE_URL" --max-time 10 > /dev/null; then
            echo "Development application is accessible"
          else
            echo "Development application is not accessible"
            exit 1
          fi

      - name: Post development deployment comment
        uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process');
            
            try {
              const serviceUrl = execSync('gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="value(status.url)"', 
                { encoding: 'utf-8' }).trim();
              
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha,
                body: `**Development Deployment Successful!**\n\n **Dev URL**: ${serviceUrl}\n\n **Build Info**:\n- Commit: ${context.sha.slice(0, 7)}\n- Environment: Development\n- Region: ${{ env.REGION }}\n- Hot Reload: Enabled\n\n *This is a development deployment with debug features enabled*`
              });
            } catch (error) {
              console.log('Failed to post deployment comment:', error.message);
            }
